### PR TITLE
Restructure overview.rst

### PR DESCRIPTION
**Pull request by MaGering**
This PR adds paragraphs to the overview chapter, which can also be referenced in external documentation (e.g. `oemof-B3`).

### CODE REVIEW

**Review by jnnr — APPROVED** [review]
Looks good!

**Review by jnnr — COMMENTED** [review]
...but you missed a heading! Line 15, "define schemas for tabular datapackages"

**Review by jnnr — CHANGES_REQUESTED** [review]
Apart from that, I am fine with the changes.

**Comment by MaGering** [comment]
> ...but you missed a heading! Line 15, "define schemas for tabular datapackages"

Thanks for finding this! Fixed with commit https://github.com/rl-institut/oemoflex/pull/81/commits/ec38db4f020d1d876d82e79cca543694531c8fc5.

**Review by jnnr — APPROVED** [review]

**Pull request merged**
